
BATTERY_WARNING_THRESHOLD = 12.0
BATTERY_CRITICAL_THRESHOLD = 11.5

LOOP_TIME_WARNING_THRESHOLD = 50.0
LOOP_TIME_CRITICAL_THRESHOLD = 100.0

MAX_FILE_SIZE_MB = 50
ALLOWED_FILE_EXTENSIONS = ['.txt', '.log']

DATA_DIR = 'data'
UPLOAD_DIR = 'data/uploads'
SAMPLE_DIR = 'data/sample'

CHART_HEIGHT = 400
CHART_COLOR_BATTERY = '#00AA00'
CHART_COLOR_LOOP_TIME = '#4488FF'
CHART_COLOR_ERROR = '#FF4444'
CHART_COLOR_WARNING = '#FF8800'
